global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'trading_bots'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'
